### ISSUE TITLE
Small typo for the dimension of V in the paper

### ISSUE THREAD

**Issue by altaykacan** [jiajie96/NeuroNURBS#1]
Hello,

thank you for publishing your work, I am a new PhD student in this field and find how you move away from the UV-grids very elegant! I think I noticed a small typo in the paper and wanted to ask whether this is the case:

On page 4, the last sentence of Section 3.1 is:

![image](https://github.com/user-attachments/assets/175e2350-502f-4961-b5aa-8255a85c743c)

In my understanding the vector $\mathbf{V}$ should actually have the dimension $m+q+1$ instead of $n+q+1$ as the number of control points in the $\mathbf{V}$-direction is defined to be $m$.

Could you please confirm this is the case? 

Thank you once again for your well-written paper and I am looking forward to the code release!

**Comment by jiajie96** [comment]
Hey dear friend, 

this is most likely a typo.
I would correct this when I update the preprint next time.

Thank you for your appreciation of this article :)
